"""date_format to upload_map table

Revision ID: 4a68096168b7
Revises: 673ed31f5b37
Create Date: 2022-08-07 00:27:08.871371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a68096168b7'
down_revision = '673ed31f5b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_map', sa.Column('date_format', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_map', 'date_format')
    # ### end Alembic commands ###
